### ISSUE TITLE
error login with username and pw in API v2

### ISSUE THREAD

**Issue by nnhieu97** [coder-amogh/pyHoneygain#6]
Hi. Thanks for great repo. But I encountered an error when logging in using the username and password in API v2. Login with v1 is still normal.
```
[/usr/local/lib/python3.9/dist-packages/pyHoneygain/hg.py](https://localhost:8080/#) in login(self, email, password)
     85         })
     86 
---> 87         token = r.json()["data"]["access_token"]
     88 
     89         return self.set_jwt_token(token) if r.ok else False

KeyError: 'data'
```

**Comment by nnhieu97** [comment]
And the following methods also return false when used with v2: `info()`, `stats()`, `stats_today()`, `balance()`

**Comment by coder-amogh** [comment]
`/v2` is only for devices, other endpoints (as of now) only work with `/v1`. 
`/v1` and `/v2` for devices return different information.
